name: DeepSource CI

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '21'

      - name: Run tests
        run: ./gradlew test

      - name: Report results to DeepSource
        run: |
          # Install DeepSource CLI
          curl https://deepsource.io/cli | sh

          # Report coverage to DeepSource
          ./bin/deepsource report --analyzer test-coverage --key java --value-file target/site/jacoco/jacoco.xml
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}



