name: Gradle CI

on:
  push:
    branches:
      - 'feature/*'
      - 'main'

jobs:
  feature-build:
#    if: startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and publish
        env:
          MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
          MVN_PASSWORD: ${{ secrets.MVN_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew --no-daemon clean assemble publish

#  main-release:
#    if: github.ref == 'refs/heads/main'
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Release
#        env:
#          MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
#          MVN_PASSWORD: ${{ secrets.MVN_PASSWORD }}
#          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
#          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
#          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
#        run: ./gradlew --no-daemon release -Prelease.useAutomaticVersion=true

